version: '3.9'
services: 
  
  eureka-server:
    container_name: eureka-server-app
    image: eureka-server-app:latest
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      ENV: prod
    tty:
      true
    restart:
      unless-stopped

  ms-aluno:
    container_name: ms-aluno-app
    image: ms-aluno-app:latest
    build:
      context: ./ms-aluno
      dockerfile: Dockerfile
    ports:
      - "8081"
    environment:
      ENV: prod
    entrypoint: /opt/bin/entrypointAluno.sh  
    depends_on:
      - eureka-server
    tty:
      true
    restart:
      unless-stopped

  ms-avaliacao:
    container_name: ms-avaliacao-app
    image: ms-avaliacao-app:latest
    build:
      context: ./ms-avaliacao
      dockerfile: Dockerfile
    ports:
      - "8082"
    environment:
      ENV: prod
    entrypoint: /opt/bin/entrypointAvaliacao.sh
    depends_on:
      - eureka-server  
    tty:
      true
    restart:
      unless-stopped

  ms-professor:
    container_name: ms-professor-app
    image: ms-professor-app:latest
    build:
      context: ./ms-professor
      dockerfile: Dockerfile
    ports:
      - "8083"
    environment:
      ENV: prod
    entrypoint: /opt/bin/entrypointProfessor.sh
    depends_on:
      - eureka-server  
    tty:
      true
    restart:
      unless-stopped

  escola-gateway:
    container_name: escola-gateway-app
    image: escola-gateway-app:latest
    build:
      context: ./escola-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ENV: prod
    entrypoint: /opt/bin/entrypointEscolaGateway.sh
    depends_on:
      - eureka-server
    tty:
      true
    restart:
      unless-stopped