version: '3.3'
services: 

  eureka-server:
    container_name: eureka-server-app
    image: eureka-server-app:v1
    restart: on-failure
    build:
      context: ./eureka-server/
      dockerfile: Dockerfile
    volumes:
      - /data/eureka-server
    ports:
      - "8761:8761"
    networks:
      - network-eureka
        
  ms-boletim:
    container_name: ms-boletim-app
    image: ms-boletim-app:v1
    restart: on-failure
    depends_on:
      - eureka-server
    build:
      context: ./ms-boletim/
      dockerfile: Dockerfile
    volumes:
      - /data/ms-boletim
    ports:
      - "8082:8082"
    networks:
      - network-eureka  

  ms-aluno:
    container_name: ms-aluno-app
    image: ms-aluno-app:v1
    restart: on-failure
    depends_on:
      - eureka-server
    build:
      context: ./ms-aluno/
      dockerfile: Dockerfile
    volumes:
      - /data/ms-aluno
    ports:
      - "8081:8081"  
    networks:
      - network-eureka
      
  eureka-gateway:
    container_name: ms-gateway-app
    image: ms-gateway-app:v1
    restart: on-failure
    depends_on:
      - ms-gateway
    build:
      context: ./ms-gateway/
      dockerfile: Dockerfile
    volumes:
      - /data/ms-gateway
    ports:
      - "8080:8080"
    networks:
      - network-eureka            
      
networks:
  network-eureka: 