version: '3.9'
services: 
  
  eureka-server:
    container_name: eureka-server-app
    image: eureka-server-app:latest
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    expose: 
      - "8761"  
    ports:
      - "8761:8761"
    environment:
      ENV: prod
    tty:
      true
    restart:
      unless-stopped

  ms-boletim:
    container_name: ms-boletim-app
    image: ms-boletim-app:latest
    build:
      context: ./ms-boletim
      dockerfile: Dockerfile
    ports:
      - "8082"
    environment:
      ENV: prod
    entrypoint: /opt/bin/entrypointBoletim.sh
    depends_on:
      - eureka-server  
    tty:
      true
    restart:
      unless-stopped

  ms-aluno:
    container_name: ms-aluno-app
    image: ms-aluno-app:latest
    build:
      context: ./ms-aluno
      dockerfile: Dockerfile
    ports:
      - "8081"
    environment:
      ENV: prod
    entrypoint: /opt/bin/entrypointAluno.sh  
    depends_on:
      - eureka-server
    tty:
      true
    restart:
      unless-stopped
      
  ms-gateway:
    container_name: ms-gateway-app
    image: ms-gateway-app:latest
    build:
      context: ./ms-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ENV: prod
    entrypoint: /opt/bin/entrypointGateway.sh
    depends_on:
      - eureka-server
    tty:
      true
    restart:
      unless-stopped