version: '3.7'
services: 

  eureka-server:
    container_name: eureka-server-app
    image: eureka-server-app:v1
    build:
      context: ./eureka-server/
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    hostname: eureka-server  
    tty:
      true
    restart:
      unless-stopped

  ms-boletim:
    container_name: ms-boletim-app
    image: ms-boletim-app:v1
    build:
      context: ./ms-boletim/
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    hostname: ms-boletim
    depends_on:
      - eureka-server
    tty:
      true
    restart:
      unless-stopped

  ms-aluno:
    container_name: ms-aluno-app
    image: ms-aluno-app:v1
    build:
      context: ./ms-aluno/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  
    hostname: ms-aluno
    depends_on:
      - eureka-server
    tty:
      true
    restart:
      unless-stopped
      
  ms-gateway:
    container_name: ms-gateway-app
    image: ms-gateway-app:v1
    build:
      context: ./ms-gateway/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    hostname: ms-gateway
    depends_on:
      - eureka-server
    tty:
      true
    restart:
      unless-stopped