version: '3.3'
services: 
  
  eureka-server:
    container_name: eureka-server-app
    image: eureka-server-app:latest
    build:
      context: ./eureka-server/
      dockerfile: Dockerfile
    volumes:
      - /data/eureka-server
    ports:
      - "8761:8761"
    networks:
      - network-eureka  
  
  ms-boletim:
    container_name: ms-boletim-app
    image: ms-boletim-app:latest
    restart: on-failure
    depends_on:
      - eureka-server
    build:
      context: ./ms-boletim/
      dockerfile: Dockerfile
    volumes:
      - /data/ms-boletim
    networks:
      - network-eureka  

  ms-aluno:
    container_name: ms-aluno-app
    image: ms-aluno-app:latest
    restart: on-failure
    depends_on:
      - eureka-server
    build:
      context: ./ms-aluno/
      dockerfile: Dockerfile
    volumes:
      - /data/ms-aluno
    networks:
      - network-eureka
      
  eureka-gateway:
    container_name: eureka-gateway-app
    image: eureka-gateway-app:latest
    restart: on-failure
    depends_on:
      - eureka-server
    build:
      context: ./eureka-gateway/
      dockerfile: Dockerfile
    volumes:
      - /data/eureka-gateway
    ports:
      - "8080:8080"
    networks:
      - network-eureka            
      
networks:
  network-eureka: 