server:
  port: 8081
spring:
  application:
    name: ms-aluno
  sleuth:
    enabled: true
    sampler:
      probability: 1
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true  
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${URI_EUREKA_SERVER:http://localhost:8761/eureka}
logging:
  level:
    org:
    springframework:
      web:
      servlet:
        DispatcherServlet: DEBUG      
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 120000
        loggerLevel: basic
info:
  app:
    name: ms-aluno
    description: Microservices Aluno
    version: "@project.version@"