spring:
  application:
    name: ms-aluno
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true  
server:
  port: 8081
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${URI_EUREKA_SERVER:http://localhost:8761/eureka}