spring:
  application:
    name: ms-professor
server:
  port: 8083
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${URI_EUREKA_SERVER:http://localhost:8761/eureka}