server:
  port: 8083
spring:
  application:
    name: ms-professor
  sleuth:
    enabled: true
    sampler:
      probability: 1
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${URI_EUREKA_SERVER:http://localhost:8761/eureka}      
logging:
  level:
    org:
    springframework:
      web:
      servlet:
        DispatcherServlet: DEBUG