spring:
  application:
    name: eureka-gateway
server:
  port: 8080
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}      
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 1800000
        loggerLevel: basic