spring:
  application:
    name: eureka-gateway
server:
  port: 8080
eureka:
  instance:
    hostname: eureka-server
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/      
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 1800000
        loggerLevel: basic        