spring:
  cloud:
    config:
      server:
        native:
          searchLocations: .
  application:
    name: CONFIGSERVER
  profiles:
    active: native
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
server:
  port: 8888