spring:
  application:
    name: ms-boletim
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 1800000
        loggerLevel: basic